name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Terraform Configuration
    uses: ./.github/workflows/tflint.yml

  tofu:
    needs: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
    - name: Setup OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_wrapper: false

    - name: OpenTofu Init
      env:
        GITHUB_TOKEN: ${{ secrets.KOSTAS_GITHUB_API_TOKEN }}
        TF_VAR_username: ${{ secrets.BACKEND_USERNAME }}
        TF_VAR_password: ${{ secrets.BACKEND_PASSWORD }}
      id: init
      run: tofu init

    - name: OpenTofu Validate
      env:
        GITHUB_TOKEN: ${{ secrets.KOSTAS_GITHUB_API_TOKEN }}
        TF_VAR_username: ${{ secrets.BACKEND_USERNAME }}
        TF_VAR_password: ${{ secrets.BACKEND_PASSWORD }}
      id: validate
      run: tofu validate -no-color

    - name: OpenTofu Plan
      env:
        GITHUB_TOKEN: ${{ secrets.KOSTAS_GITHUB_API_TOKEN }}
        TF_VAR_username: ${{ secrets.BACKEND_USERNAME }}
        TF_VAR_password: ${{ secrets.BACKEND_PASSWORD }}
      id: plan
      run: tofu plan | tee tofu_plan_output.txt
      continue-on-error: true

    - name: Print job summary
      uses: sgametrio/terraform-summary-action@main
      with:
        log-file: tofu_plan_output.txt
        # Optional
        title: Tofu Job Summary